<?php
/**
 * language for install
 */
$lang = array(
"pls_reinstall_program"=>"请重新安装程序包",
"title"=>"欢迎使用PHPB2B电子商务系统安装程序",
"not_empty_passwd"=>"管理员密码不能为空！",
"not_empty_db"=>"数据库不能为空",
"installing"=>"正在安装...",
"not_full_files"=>"安装文件不完整，请下载后重新尝试！",
"dir_cant_write"=>"目录不可写",
"right_ok"=>"权限正确",
"pls_input_admin"=>"请输入管理员账户",
"pls_input_admin_passwd"=>"请输入管理员密码",
"cant_open_conf"=>"配置文件 ua.conf 不能打开！",
"conf_write_false"=>"配置文件 ua.conf 写入失败！",
"core_sample_not_exists"=>"配置文件 core.sample.php 不存在",
"db_sample_right"=>"配置文件 db.sample.php 不存在",
"not_enough_right"=>"配置文件 core.php 权限不够！",
"db_file_right"=>"数据库配置文件 db.php 权限不够！",
"db_error"=>"数据库错误:",
"pls_select_db"=>"请提供数据库名称！",
"db_file_not_exists"=>"数据库文件不存在",
"db_cn_error"=>"数据库连接错误",
"data_backuped"=>"原有的数据已经备份到 ",
"sql_open_error"=>"sql 文件打开错误",
"zip_open_error"=>"压缩文件打开错误",
"super_admin"=>"超级管理员",
"ualinkphp"=>"PHPB2B",
"ualinkb2b_demo"=>"PHP B2B电子商务网演示",
"first_sell"=>"第一条供应",
"first_sell_del"=>"第一条供应,你可以删除该信息",
"first_buy"=>"第一条求购",
"first_buy_del"=>"你可以删除该信息",
"ualinkb2b"=>"PHPB2B NETWORK",
"company_desc"=>"电子商务了吗？PHPB2B 将助您开拓电子商务之路",
"db_not_exists"=>"数据库不存在",
"install_false"=>"安装失败，请检查原因后重新执行此程序",
"pls_input_site_desc"=>"请输入网站的基本资料",
"pls_select_lang"=>"选择安装语言文件",
"site_name"=>"网站名称",
"site_url"=>"网站地址",
"bbs_set"=>"商业论坛",
"bbs_url"=>"论坛地址",
"admin_account"=>"管理员帐号",
"admin_passwd"=>"管理员密码",
"start_install"=>"开始安装",
"check_file_right"=>"检查文件权限",
"view_help"=>"查看安装帮助",
"ualink_wel"=>"<a href=\"http://www.phpb2b.com/\" target=\"_blank\">PHPB2B 电子商务应用程序</a>，为您搭建方便快捷的电子商务平台",
"db_prefix"=>"数据表前缀",
"do_not_mod"=>"最好不要改动",
"default_host"=>"默认为本机",
"db_host"=>"数据库主机",
"db_pass"=>"密码",
"db_user"=>"用户名",
"if_create_new_db"=>"是否新建库",
"pls_input_db_connect"=>"请输入数据库连接的详细信息",
"if_save_old_data"=>"如果你想保留旧的数据，请务必另外建立一个数据库，否则将更新友邻的所有现有数据(但不会删除非友邻数据)。",
"if_set_forum"=>"如果设置了商业论坛，最好保持帐号和密码跟论坛管理员一致",
"db_name"=>"数据库名",
"not_support"=>"暂时不提供",
"discuz_bbs"=>"DISCUZ论坛",
"phpwind_bbs"=>"PHPWIND论坛",
"get_random_pwd"=>"随机生成安全密码",
"first_sell"=>"第一条供应",
"first_buy"=>"第一条求购",
"first_del_content"=>"你可以删除该信息",
"ualink_b2b"=>"PHPB2B 电子商务网",
"ualink_b2b_content"=>"电子商务了吗？PHPB2B 将助您开拓电子商务之路",
"retry_install"=>"<h2>重新安装?</h2>",
"a_new_b2b_site"=>"一个新的B2B电子商务网",
"db1049"=>"数据库不存在",
"db1045"=>"数据库用户名或者密码错误",
"delete_and_install"=>"您必须先删除 data 目录下的 install.lock 文件才能继续进行安装,如果已经删除请点击 <a href='install.php?language=".(isset($_GET['language'])?$_GET['language']:-1)."'>继续安装</a>.",
);
?>