<?php
/**
 * language for install
 */
$lang = array(
"pls_reinstall_program"=>"請重新安裝程序包",
"title"=>"歡迎使用PHPB2B電子商務系統安裝程序",
"not_empty_passwd"=>"管理員密碼不能為空！",
"not_empty_db"=>"數據庫不能為空",
"installing"=>"正在安裝...",
"not_full_files"=>"安裝文件不完整，請下載後重新嘗試！",
"dir_cant_write"=>"目錄不可寫",
"right_ok"=>"權限正確",
"pls_input_admin"=>"請輸入管理員賬戶",
"pls_input_admin_passwd"=>"請輸入管理員密碼",
"cant_open_conf"=>"配置文件 ua.conf 不能打開！",
"conf_write_false"=>"配置文件 ua.conf 寫入失敗！",
"core_sample_not_exists"=>"配置文件 core.sample.php 不存在",
"db_sample_right"=>"配置文件 db.sample.php 不存在",
"not_enough_right"=>"配置文件 core.php 權限不夠！",
"db_file_right"=>"數據庫配置文件 db.php 權限不夠！",
"db_error"=>"數據庫錯誤:",
"pls_select_db"=>"請提供數據庫名稱！",
"db_file_not_exists"=>"數據庫文件不存在",
"db_cn_error"=>"數據庫連接錯誤",
"data_backuped"=>"原有的數據已經備份到 ",
"sql_open_error"=>"sql 文件打開錯誤",
"zip_open_error"=>"壓縮文件打開錯誤",
"super_admin"=>"超級管理員",
"ualinkphp"=>"PHPB2B",
"ualinkb2b_demo"=>"PHP B2B電子商務網演示",
"first_sell"=>"第一條供應",
"first_sell_del"=>"第一條供應,你可以刪除該信息",
"first_buy"=>"第一條求購",
"first_buy_del"=>"你可以刪除該信息",
"ualinkb2b"=>"PHPB2B NETWORK",
"company_desc"=>"電子商務了嗎？PHPB2B 將助您開拓電子商務之路",
"db_not_exists"=>"數據庫不存在",
"install_false"=>"安裝失敗，請檢查原因後重新執行此程序",
"pls_input_site_desc"=>"請輸入網站的基本資料",
"pls_select_lang"=>"選擇安裝語言文件",
"site_name"=>"網站名稱",
"site_url"=>"網站地址",
"bbs_set"=>"商業論壇",
"bbs_url"=>"論壇地址",
"admin_account"=>"管理員帳號",
"admin_passwd"=>"管理員密碼",
"start_install"=>"開始安裝",
"check_file_right"=>"檢查文件權限",
"view_help"=>"查看安裝幫助",
"ualink_wel"=>"<a href=\"http://www.phpb2b.com/\" target=\"_blank\">PHPB2B 電子商務應用程序</a>，為您搭建方便快捷的電子商務平臺",
"db_prefix"=>"數據表前綴",
"do_not_mod"=>"最好不要改動",
"default_host"=>"默認為本機",
"db_host"=>"數據庫主機",
"db_pass"=>"密碼",
"db_user"=>"用戶名",
"if_create_new_db"=>"是否新建庫",
"pls_input_db_connect"=>"請輸入數據庫連接的詳細信息",
"if_save_old_data"=>"如果你想保留舊的數據，請務必另外建立一個數據庫，否則將更新友鄰的所有現有數據(但不會刪除非友鄰數據)。",
"if_set_forum"=>"如果設置了商業論壇，最好保持帳號和密碼跟論壇管理員一致",
"db_name"=>"數據庫名",
"not_support"=>"暫時不提供",
"discuz_bbs"=>"DISCUZ論壇",
"phpwind_bbs"=>"PHPWIND論壇",
"get_random_pwd"=>"隨機生成安全密碼",
"first_sell"=>"第一條供應",
"first_buy"=>"第一條求購",
"first_del_content"=>"你可以刪除該信息",
"ualink_b2b"=>"PHPB2B 電子商務網",
"ualink_b2b_content"=>"電子商務了嗎？PHPB2B 將助您開拓電子商務之路",
"retry_install"=>"<h2>重新安裝?</h2>",
"a_new_b2b_site"=>"一個新的B2B電子商務網",
"db1049"=>"數據庫不存在",
"db1045"=>"數據庫用戶名或者密碼錯誤",
);
?>