<?php
/**
 * language for install
 */
$lang = array (
"pls_reinstall_program" => "Please reinstall the package",
"title" => "Welcome to PHPB2B e-commerce systems installation program",
"not_empty_passwd" => "administrator password can not be empty!" ,
"not_empty_db" => "database can not be empty" ,
"installing" => "is being installed ...",
"not_full_files" => "installation file is not complete, please download and re-try!" ,
"dir_cant_write" => "Directory not writable",
"right_ok" => "access right",
"pls_input_admin" => "Please enter an administrator account",
"pls_input_admin_passwd" => "Please enter the administrator password",
"cant_open_conf" => "configuration file ua.conf can not be opened!" ,
"conf_write_false" => "failed to write configuration files ua.conf!" ,
"core_sample_not_exists" => "configuration file core.sample.php does not exist",
"db_sample_right" => "configuration file db.sample.php does not exist",
"not_enough_right" => "configuration file core.php permissions enough!" ,
"db_file_right" => "database configuration file db.php insufficient permissions!" ,
"db_error" => "Database Error:",
"pls_select_db" => "Please provide a database name!" ,
"db_file_not_exists" => "database file does not exist",
"db_cn_error" => "database connection error",
"data_backuped" => "the original data has been backed up to",
"sql_open_error" => "sql file open error",
"zip_open_error" => "compressed file open error",
"super_admin" => "super administrator",
"ualinkphp" => "PHPB2B",
"ualinkb2b_demo" => "PHP B2B e-commerce network demonstration" ,
"first_sell" => "first supply",
"first_sell_del" => "first supply, you can delete the message" ,
"first_buy" => "first buy",
"first_buy_del" => "You can delete the message" ,
"ualinkb2b" => "PHPB2B NETWORK",
"company_desc" => "e-commerce了吗? PHPB2B will help you to develop e-commerce Road" ,
"db_not_exists" => "database does not exist",
"install_false" => "Installation failed, please check the reason for the re-implementation of this program" ,
"pls_input_site_desc" => "Please enter the site's basic information" ,
"pls_select_lang" => "choose to install the language file",
"site_name" => "Site Name",
"site_url" => "website address",
"bbs_set" => "Business Forum",
"bbs_url" => "group address",
"admin_account" => "administrator account",
"admin_passwd" => "administrator password",
"start_install" => "Start Installation",
"check_file_right" => "Check the file permissions",
"view_help" => "view the installation help",
"ualink_wel "=>"<a href='http://www.phpb2b.com/' target=' _blank'> PHPB2B e-business applications </ a>, convenient for you to build e-commerce platform " ,
"db_prefix" => "table prefix",
"do_not_mod" => "better not to change",
"default_host" => "default-based machines" ,
"db_host" => "database host",
"db_pass" => "password",
"db_user" => "User Name",
"if_create_new_db" => "whether the new bank",
"pls_input_db_connect" => "Please enter the database connection details",
"if_save_old_data" => "If you want to keep the old data, please be sure to create a separate database, or they will update the neighboring all available data (but does not remove the non-neighboring data).",
"if_set_forum" => "If you set the business forum, best to keep the administrator account and password in line with the Forum" ,
"db_name" => "database name",
"not_support" => "temporarily not available",
"discuz_bbs" => "DISCUZ Forum" ,
"phpwind_bbs" => "PHPWIND Forum" ,
"get_random_pwd" => "randomly generated security codes" ,
"first_sell" => "first supply",
"first_buy" => "first buy",
"first_del_content" => "You can delete the message" ,
"ualink_b2b" => "PHPB2B E-Commerce Network",
"ualink_b2b_content" => "e-commerce? PHPB2B will help you to develop e-commerce Road",
"retry_install "=>"<h2> re-install? </h2>",
"a_new_b2b_site" => "a new B2B e-commerce network",
"db1049" => "database does not exist",
"db1045" => "database user name or password error",
"delete_and_install"=>"Before install, you must delete install.lock under data directory, and <a href='install.php?language=".$_GET['language']."'>click here</a> to continue to install.",
);
?>