<?php
/**
 * language for install
 */
$lang = array(
"ualinkphp"=>"Ualink",
"pls_reinstall_program" => "Please re-installation package", 
"title" => "Welcome to the ualinkb2b php e-commerce system installation process" ,
"not_empty_passwd" => "administrator password can not be empty!" ,
"not_empty_db" => "database can not be empty", 
"installing" => "is being installed ...", 
"not_full_files" => "installation files are incomplete, please download the re-try!" ,
"dir_cant_write" => "directory can not write", 
"right_ok" => "proper authority", 
"pls_input_admin" => "Please enter the administrator account", 
"pls_input_admin_passwd" => "Please enter an administrator password" ,
"cant_open_conf" => "profile ua.conf can not open!" ,
"conf_write_false" => "profile ua.conf write failure!" ,
"core_sample_not_exists" => "core.sample.php profile does not exist" ,
"db_sample_right" => "db.sample.php profile does not exist" ,
"not_enough_right" => "profile core.php authority enough!" ,
"db_file_right" => "database profile db.php authority not enough!" ,
"db_error" => "database error:" ,
"pls_select_db" => "Please provide the name of the database!" ,
"db_file_not_exists" => "database file does not exist" ,
"db_cn_error" => "database connection error", 
"data_backuped" => "original data is backed up to" ,
"sql_open_error" => "sql file open error", 
"zip_open_error" => "open compressed files wrong", 
"super_admin" => "super administrator" ,
"ualinkphp" => "ualinkb2b php", 
"ualinkb2b_demo" => "ualinkb2b demonstration of e-commerce network", 
"first_sell" => "First of supply", 
"first_sell_del" => "First of supply, you can delete the message", 
"first_buy" => "The first purchase" ,
"first_buy_del" => "You can delete the message" ,
"ualinkb2b" => "ualinkb2b php electronic commerce network" ,
"company_desc" => "the e-commerce?» ualinkb2b electronic commerce network will help you explore the road of e-commerce" , 
"db_not_exists" => "database does not exist" ,
"install_false" => "installation, please check again after the implementation of the reasons for this process", 
"pls_input_site_desc" => "Please enter the site of the basic data", 
"pls_select_lang" => "choose to install language paper" ,
"site_name" => "site name", 
"site_url" => "website address", 
"bbs_set" => "Business Forum", 
"bbs_url" => "Forum address", 
"admin_account" => "administrator account", 
"admin_passwd" => "administrator password" ,
"start_install" => "start the installation" ,
"check_file_right" => "check the file permissions" ,
"view_help" => "Show installation help", 
"ualink_wel"=>"<a href=\"http://www.ualink.org/\" target=_blank>ualinkb2b php e-commerce applications </ a>, for your convenience structures E-commerce platform",  
"db_prefix" => "data table prefix" ,
"do_not_mod" => "It is best not to change", 
"default_host" => "default-based machine", 
"db_host" => "database host" ,
"db_pass" => "password" ,
"db_user" => "user name" ,
"if_create_new_db" => "whether to create the new database" ,
"pls_input_db_connect" => "Please enter the database connection details" ,
"if_save_old_data" => "If you want to keep the old data, please be sure to create a separate database, otherwise, they will update the ualinkb2b all available data (but not delete the non-ualink data).", 
"if_set_forum" => "If the installation of the Business Forum, the best to maintain ID and password in line with the group manager" ,
"db_name" => "database name" ,
"not_support" => "not to provide" ,
"discuz_bbs" => "DISCUZ Forum", 
"phpwind_bbs" => "PHPWIND Forum",
"get_random_pwd"=>"Randomly generated security password",
"first_sell" => "First of supply", 
"first_buy" => "The first purchase",
"first_del_content" => "You can delete the message",
"ualink_b2b" => "ualink php electronic commerce network",
"ualink_b2b_content" => "the ualinkb2b electronic commerce network will help you explore the road of e-commerce",
);
?>