<?php
$menus = array(
0=>array(
		"ename"=>"home","url"=>"","cname"=>"首页","items"=>array(
			array("ename"=>"quickaction","show"=>true,"cname"=>"快速操作","items"=>array(
				array("cname"=>"会员管理","url"=>"member.php?action=list"),
				array("cname"=>"产品管理","url"=>"product.php?action=list"),
				array("cname"=>"供求管理","url"=>"trade.php?action=list"),
				array("cname"=>"公司库管理","url"=>"company.php?action=list"),
				array("cname"=>"行业分类管理","url"=>"industry.php?action=list"),
				array("cname"=>"本网动态","url"=>"news.php?action=list"),
				array("cname"=>"关键词管理","url"=>"keyword.php?action=list"),
				array("cname"=>"广告管理","url"=>"ad.php?action=list"),
				array("cname"=>"展会管理","url"=>"fair.php?action=list"),
				array("cname"=>"计划任务","url"=>"backup.php?action=home"),
				array("cname"=>"基本设置","url"=>"setting.php?action=basic"))),
				array("cname"=>"用户日志","ename"=>"visitlog","items"=>array(
				array("cname"=>"用户登陆日志","url"=>"memberlog.php?action=list"),
				array("cname"=>"管理员操作日志","url"=>"adminlog.php?action=list"))
			)
		)
	),
1=>array(
		"ename"=>"basic","url"=>"setting.php?action=basic","cname"=>"系统设置","items"=>array(
			array("ename"=>"setting","show"=>false,"cname"=>"系统设置","items"=>array(
				array("cname"=>"基本设置","url"=>"setting.php?action=basic"),
				array("cname"=>"邮件设置","url"=>"setting.php?action=mail"),
				array("cname"=>"注册与访问","url"=>"setting.php?action=permission"),
				array("cname"=>"计划任务","url"=>"backup.php?action=home"),
				array("cname"=>"Google Sitemap","url"=>"sitemap.php?action=set"),
			)),
			array("ename"=>"iodatas","cname"=>"系统工具","items"=>array(
				array("cname"=>"导入会员","url"=>"io.php?action=import","title"=>"从整合软件导入会员数据"),
				array("cname"=>"更新统计数据","url"=>"stat.php","title"=>"手动更新网站数据统计"),
			)),
	)),
2=>array(
		"ename"=>"datas","url"=>"trade.php?action=list","cname"=>"信息库","items"=>array(
			array("ename"=>"trade","show"=>false,"cname"=>"供求信息","items"=>array(
				array("cname"=>"供求管理","url"=>"trade.php?action=list"),
				array("cname"=>"添加供求","url"=>"trade.php?action=mod"),
				array("cname"=>"供求统计(Beta)","url"=>"trade.php?action=stat"),
			)),
			array("ename"=>"product","cname"=>"产品中心","items"=>array(
				array("cname"=>"产品管理","url"=>"product.php?action=list"),
				array("cname"=>"添加产品","url"=>"product.php?action=mod"),

			)),
			array("ename"=>"company","cname"=>"公司库","items"=>array(
				array("cname"=>"公司库管理","url"=>"company.php?action=list"),
				array("cname"=>"添加公司","url"=>"company.php?action=mod"),
				array("cname"=>"公司类型","url"=>"companytype.php?action=list"),
				array("cname"=>"添加类型","url"=>"companytype.php?action=mod"),
				array("cname"=>"企业视频","url"=>"company.php?action=vcr"),
			)),
			array("ename"=>"market","cname"=>"市场大全","items"=>array(
				array("cname"=>"市场库管理","url"=>"market.php?action=list"),
				array("cname"=>"添加市场","url"=>"market.php?action=mod"),
			)),
			array("ename"=>"job","cname"=>"招聘信息","items"=>array(
				array("cname"=>"招聘信息管理","url"=>"job.php?action=list"),
			)),
			array("ename"=>"member","cname"=>"会员中心","items"=>array(
				array("cname"=>"会员管理","url"=>"member.php?action=list"),
				array("cname"=>"添加会员","url"=>"member.php?action=mod"),
				array("cname"=>"会员类型","url"=>"membertype.php?action=list"),
				array("cname"=>"添加类型","url"=>"membertype.php?action=mod")
			)),
			array("ename"=>"member","cname"=>"展会信息","items"=>array(
				array("cname"=>"展会管理","url"=>"fair.php?action=list"),
				array("cname"=>"展会类型管理","url"=>"fairtype.php?action=list"),
				array("cname"=>"添加展会","url"=>"fair.php?action=mod"),
				array("cname"=>"添加展会类型","url"=>"fairtype.php?action=mod")
			)),
			array("ename"=>"order","cname"=>"用户订单","items"=>array(
				array("cname"=>"订单管理","url"=>"order.php?action=list")
			)),
			array("ename"=>"keyword","cname"=>"关键词","items"=>array(
				array("cname"=>"关键词列表","url"=>"keyword.php?action=list"),
				array("cname"=>"关键词竞价","url"=>"keywordship.php?action=list"),
				array("cname"=>"添加竞价","url"=>"keywordship.php?action=mod")
			)),
)),
3=>array(
		"ename"=>"ads","url"=>"ad.php?action=list","cname"=>"广告","items"=>array(
			array("ename"=>"ads","show"=>false,"cname"=>"广告位置","items"=>array(
				array("cname"=>"广告位置","url"=>"adzone.php?action=list"),
				array("cname"=>"添加位置","url"=>"adzone.php?action=mod"),
			)),
			array("ename"=>"ads","show"=>false,"cname"=>"在线广告","items"=>array(
				array("cname"=>"广告列表","url"=>"ad.php?action=list"),
				array("cname"=>"添加广告","url"=>"ad.php?action=mod"),
			)),
		)),
4=>array(
		"ename"=>"news","url"=>"news.php?action=list","cname"=>"新闻资讯","items"=>array(
			array("ename"=>"news","show"=>false,"cname"=>"新闻资讯","items"=>array(
				array("cname"=>"所有新闻","url"=>"news.php?action=list"),
				array("cname"=>"添加新闻","url"=>"news.php?action=mod"),
			)),
			array("ename"=>"newstypes","cname"=>"资讯类别","items"=>array(
				array("cname"=>"资讯类别","url"=>"newstype.php?action=list"),
				array("cname"=>"添加分类","url"=>"newstype.php?action=mod"),
			)),
			array("ename"=>"companynews","cname"=>"企业新闻","items"=>array(
				array("cname"=>"新闻管理","url"=>"companynews.php?action=list"),
			)),
			array("ename"=>"companymessages","cname"=>"企业评论","items"=>array(
				array("cname"=>"评论管理","url"=>"companymessage.php?action=list"),
			)),
	)),
5=>array(
		"ename"=>"services","url"=>"service.php?action=list","cname"=>"在线服务","items"=>array(
			array("ename"=>"leavewords","show"=>false,"cname"=>"留言管理","items"=>array(
				array("cname"=>"用户留言","url"=>"service.php?action=list"),
			)),
			array("ename"=>"helps","cname"=>"网站助手","items"=>array(
				array("cname"=>"帮助类别","url"=>"helptype.php?action=list"),
				array("cname"=>"添加类别","url"=>"helptype.php?action=mod"),
				array("cname"=>"帮助文件","url"=>"help.php?action=list"),
				array("cname"=>"添加帮助","url"=>"help.php?action=mod"),
			)),
		)),
6=>array(
		"ename"=>"templets","url"=>"templet.php?action=list","cname"=>"网站模板","items"=>array(
			array("ename"=>"company_templets","show"=>false,"cname"=>"企业模板","items"=>array(
				array("cname"=>"会员主页模板","url"=>"templet.php?action=list"),
				array("cname"=>"添加会员主页模板","url"=>"templet.php?action=mod"),
			)),
		)),
7=>array(
		"ename"=>"links","url"=>"friendlink.php?action=list","cname"=>"其他","items"=>array(
			array("ename"=>"membership_links","cname"=>"友情链接","items"=>array(
				array("cname"=>"链接管理","url"=>"friendlink.php?action=list"),
				array("cname"=>"添加链接","url"=>"friendlink.php?action=mod"),
			)),
			array("ename"=>"userpages","cname"=>"自定义页面","items"=>array(
				array("cname"=>"撰写页面","url"=>"userpage.php?action=mod"),
				array("cname"=>"页面管理","url"=>"userpage.php?action=list"),
			)),
			array("ename"=>"staticset","cname"=>"静态缓存","items"=>array(
				array("cname"=>"静态文件管理","url"=>"mkstatic.php?action=staticfiles"),
				array("cname"=>"清除编译文件","url"=>"mkstatic.php?action=clearcompile"),
			)),
			array("ename"=>"industry","cname"=>"行业类别","items"=>array(
				array("cname"=>"类别管理","url"=>"industry.php?action=list"),
				array("cname"=>"更新行业数据","url"=>"industry.php?action=update"),

				array("cname"=>"添加行业类别","url"=>"industry.php?action=mod"),
				array("cname"=>"生成行业下拉数据","url"=>"industry.php?action=industryxml"),

				array("cname"=>"生成省市下拉数据","url"=>"industry.php?action=areaxml"),
			)),
			array("ename"=>"area","cname"=>"地区管理","items"=>array(
				array("cname"=>"地区列表","url"=>"area.php?action=list"),
				array("cname"=>"生成省市下拉数据","url"=>"industry.php?action=areaxml"),
				array("cname"=>"更新地区缓存","url"=>"area.php?action=update"),
			)),
			array("ename"=>"announce","cname"=>"公告管理<img src=\"images/new2.gif\" border=0 />","items"=>array(
				array("cname"=>"公告列表","url"=>"announce.php?action=list"),
				array("cname"=>"新增公告","url"=>"announce.php?action=mod"),
			)),
			array("ename"=>"adminer","cname"=>"管理员","items"=>array(
				array("cname"=>"管理员列表","url"=>"adminer.php"),
				array("cname"=>"修改密码","url"=>"adminer.php?action=password"),
			)),
		)),
);

?>